config/routes.rb
Rails.application.routes.draw do
  resources :studnets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/studnet.rb
class Studnet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/studnets_controller.rb
class StudnetsController < ApplicationController
  before_action :set_studnet, only: [:show, :edit, :update, :destroy]

  # GET /studnets
  # GET /studnets.json
  def index
    @studnets = Studnet.all
  end

  # GET /studnets/1
  # GET /studnets/1.json
  def show
  end

  # GET /studnets/new
  def new
    @studnet = Studnet.new
  end

  # GET /studnets/1/edit
  def edit
  end

  # POST /studnets
  # POST /studnets.json
  def create
    @studnet = Studnet.new(studnet_params)

    respond_to do |format|
      if @studnet.save
        format.html { redirect_to @studnet, notice: 'Studnet was successfully created.' }
        format.json { render :show, status: :created, location: @studnet }
      else
        format.html { render :new }
        format.json { render json: @studnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studnets/1
  # PATCH/PUT /studnets/1.json
  def update
    respond_to do |format|
      if @studnet.update(studnet_params)
        format.html { redirect_to @studnet, notice: 'Studnet was successfully updated.' }
        format.json { render :show, status: :ok, location: @studnet }
      else
        format.html { render :edit }
        format.json { render json: @studnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studnets/1
  # DELETE /studnets/1.json
  def destroy
    @studnet.destroy
    respond_to do |format|
      format.html { redirect_to studnets_url, notice: 'Studnet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studnet
      @studnet = Studnet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studnet_params
      params.require(:studnet).permit(:lanme, :fname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/studnets_helper.rb
module StudnetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/studnets/_form.html.erb
<%= form_with(model: studnet, local: true) do |form| %>
  <% if studnet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(studnet.errors.count, "error") %> prohibited this studnet from being saved:</h2>

      <ul>
      <% studnet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lanme %>
    <%= form.text_field :lanme, id: :studnet_lanme %>
  </div>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname, id: :studnet_fname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :studnet_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/studnets/edit.html.erb
<h1>Editing Studnet</h1>

<%= render 'form', studnet: @studnet %>

<%= link_to 'Show', @studnet %> |
<%= link_to 'Back', studnets_path %>

app/views/studnets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Studnets</h1>

<table>
  <thead>
    <tr>
      <th>Lanme</th>
      <th>Fname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studnets.each do |studnet| %>
      <tr>
        <td><%= studnet.lanme %></td>
        <td><%= studnet.fname %></td>
        <td><%= studnet.email %></td>
        <td><%= link_to 'Show', studnet %></td>
        <td><%= link_to 'Edit', edit_studnet_path(studnet) %></td>
        <td><%= link_to 'Destroy', studnet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Studnet', new_studnet_path %>

app/views/studnets/new.html.erb
<h1>New Studnet</h1>

<%= render 'form', studnet: @studnet %>

<%= link_to 'Back', studnets_path %>

app/views/studnets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lanme:</strong>
  <%= @studnet.lanme %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @studnet.fname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @studnet.email %>
</p>

<%= link_to 'Edit', edit_studnet_path(@studnet) %> |
<%= link_to 'Back', studnets_path %>